#!/usr/bin/env python3
"""Regenerate the TUI mascot's frame data from the source gif.

Two outputs, one per renderer:

  src/tui/mascot_frames.zig   quantized half-block cells, baked into the binary
  src/tui/mascot/frame-NN.png per-frame pngs for the kitty-graphics path

Run from the repo root with the source gif as the only argument:

    python3 src/tui/mascot/gen_frames.py path/to/clanker-zooming.gif

Needs Pillow. The checked-in outputs are what the build uses, so this only has
to be rerun when the artwork itself changes.
"""

import os
import sys

from PIL import Image, ImageEnhance

COLS = 21
ROWS = 10
# Cell aspect: one row is two stacked pixels, so the sample grid is COLS x ROWS*2.
PNG_SIZE = (192, 192)

# The artwork's own colours, sampled from the gif: dark outline, three body
# greys, the cyan eye, the tan chest patch, and the dust puffs. Quantizing to
# these rather than letting the resampler average is what keeps the thin limbs
# readable at 21x10 -- a plain LANCZOS downsample turns the whole robot into
# uniform grey mush.
PALETTE = [
    (0x2C, 0x30, 0x38),  # 0 outline
    (0x5C, 0x67, 0x76),  # 1 body shadow
    (0x8A, 0x98, 0xAA),  # 2 body mid
    (0xBA, 0xC6, 0xD4),  # 3 body highlight
    (0x4F, 0xD8, 0xE8),  # 4 eye
    (0xC9, 0xA8, 0x78),  # 5 chest patch
    (0xCF, 0xC4, 0xB0),  # 6 dust
]
TRANSPARENT = 0xF
# Below this alpha a sample is background rather than robot. Tuned by eye:
# lower and the antialiased outline smears into a halo, higher and the
# antenna and fingers drop out entirely.
ALPHA_CUTOFF = 0.45


def load_frames(path):
    im = Image.open(path)
    out = []
    for i in range(getattr(im, "n_frames", 1)):
        im.seek(i)
        out.append(im.convert("RGBA"))
    return out


def union_crop(frames):
    """Crop every frame to one shared bbox so the robot doesn't jitter."""
    box = None
    for f in frames:
        b = f.getchannel("A").getbbox()
        if b is None:
            continue
        box = b if box is None else (
            min(box[0], b[0]), min(box[1], b[1]),
            max(box[2], b[2]), max(box[3], b[3]),
        )
    if box is None:
        raise SystemExit("every frame is fully transparent")
    return [f.crop(box) for f in frames]


def nearest(rgb):
    return min(
        range(len(PALETTE)),
        key=lambda i: sum((PALETTE[i][c] - rgb[c]) ** 2 for c in range(3)),
    )


def to_cells(img):
    small = img.resize((COLS, ROWS * 2), Image.BOX)
    small = ImageEnhance.Contrast(small).enhance(1.35)
    small = ImageEnhance.Color(small).enhance(1.5)
    px = small.load()

    def sample(x, y):
        p = px[x, y]
        if p[3] / 255.0 < ALPHA_CUTOFF:
            return TRANSPARENT
        return nearest(p[:3])

    out = bytearray()
    for r in range(ROWS):
        for c in range(COLS):
            out.append((sample(c, r * 2) << 4) | sample(c, r * 2 + 1))
    return bytes(out)


def write_zig(path, frames_cells):
    lines = [
        "//! Generated by src/tui/mascot/gen_frames.py -- do not edit by hand.",
        "//!",
        "//! The mascot as terminal cells, for terminals without kitty graphics.",
        "//! One byte per cell, high nibble the upper half-block's colour and low",
        "//! nibble the lower half's, both indices into `palette`; 0xF is",
        "//! transparent (leave whatever is underneath alone).",
        "",
        f"pub const cols: u16 = {COLS};",
        f"pub const rows: u16 = {ROWS};",
        f"pub const frame_count: usize = {len(frames_cells)};",
        "",
        "/// Sampled from the source artwork. Indices, not a ramp: nothing here",
        "/// assumes an ordering.",
        "pub const palette = [_]u24{",
    ]
    for (r, g, b), name in zip(PALETTE, [
        "outline", "body shadow", "body mid", "body highlight",
        "eye", "chest patch", "dust",
    ]):
        lines.append(f"    0x{r:02X}{g:02X}{b:02X}, // {name}")
    lines += [
        "};",
        "",
        "pub const transparent: u8 = 0xF;",
        "",
        f"pub const frames = [frame_count][rows * cols]u8{{",
    ]
    for fi, cells in enumerate(frames_cells):
        lines.append(f"    // frame {fi}")
        lines.append("    .{")
        for r in range(ROWS):
            row = cells[r * COLS:(r + 1) * COLS]
            body = " ".join(f"0x{b:02X}," for b in row)
            lines.append(f"        {body}")
        lines.append("    },")
    lines += ["};", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(lines))


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    src = sys.argv[1]
    here = os.path.dirname(os.path.abspath(__file__))
    frames = union_crop(load_frames(src))

    cells = [to_cells(f) for f in frames]
    write_zig(os.path.join(os.path.dirname(here), "mascot_frames.zig"), cells)

    for i, f in enumerate(frames):
        # Padded to a square so the kitty path and the half-block path frame
        # the robot identically; the cell grid is very nearly square too.
        w, h = f.size
        side = max(w, h)
        sq = Image.new("RGBA", (side, side), (0, 0, 0, 0))
        sq.alpha_composite(f, ((side - w) // 2, side - h))
        sq.resize(PNG_SIZE, Image.LANCZOS).save(
            os.path.join(here, f"frame-{i:02d}.png"), optimize=True
        )

    print(f"{len(frames)} frames -> mascot_frames.zig + {len(frames)} pngs")


if __name__ == "__main__":
    main()
