// shadcn-shaped components for this page.
//
// shadcn/ui ships React components over Radix, generated by a CLI that assumes
// TypeScript and a bundler. This page is preact/htm plus the DOM factory in
// core/ui.js, inside a WASM guest that embeds every file at comptime, so what
// is ported is the shape that makes shadcn pleasant to use rather than the
// library: a variant table, a class merge, and call sites that read as
// components instead of as attribute soup.
//
// The variant table spells the cabinet's control classes today (`primary`,
// `secondary`) because ui/app/app.css still owns them for every view that has
// not moved yet. When the last of that sheet goes they become utilities in
// ui/app/tailwind.src.css, and this file is the one place that changes.
//
// Only components with a caller exist here. A variant is added the way a
// plugin is: when something needs it.

import { T } from "./ui.js";

/// Join the class lists that are not empty. shadcn uses clsx plus
/// tailwind-merge to resolve conflicting utilities; a component here chooses
/// its own classes and the caller's go last, so a plain join says the same
/// thing without a dependency.
export function cn() {
  var out = [];
  for (var i = 0; i < arguments.length; i++) {
    if (arguments[i]) out.push(arguments[i]);
  }
  return out.join(" ");
}

/// A small cva: `variants({ variant, class })` returns the class list for one
/// call. `defaults` fills a prop the caller left out.
export function variants(config) {
  var defaults = config.defaults || {};
  return function (props) {
    props = props || {};
    var out = [config.base || ""];
    for (var name in config.variants) {
      var value = props[name] == null ? defaults[name] : props[name];
      var table = config.variants[name];
      if (value && table[value]) out.push(table[value]);
    }
    out.push(props.class || "");
    return cn.apply(null, out);
  };
}

/// The button's variants, in the cabinet's own words: shadcn's `default` is
/// the blue actuator here, `secondary` the plate, `destructive` the danger
/// fill, and `secondary-danger` a danger reading on the plate.
export var buttonVariants = variants({
  defaults: { variant: "secondary" },
  variants: {
    variant: {
      primary: "primary",
      secondary: "secondary",
      danger: "danger",
      "secondary-danger": "secondary danger",
    },
  },
});

/// A `<button>`, with the variant table applied and every other prop passed
/// through as an attribute (`type` defaults to button, since nothing in this
/// page submits a form).
export function button(opts) {
  var props = opts || {};
  var attrs = { type: props.type || "button", class: buttonVariants(props) };
  for (var key in props) {
    if (key !== "type" && key !== "variant" && key !== "class") attrs[key] = props[key];
  }
  var children = Array.prototype.slice.call(arguments, 1);
  return T.button.apply(null, [attrs].concat(children));
}
